In [1]:
import numpy as np

1.

In [3]:
A = np.array([[4,5,6,7],
              [2,-3,2,3],
              [3,4,5,6],
              [4,7,8,9]])
print("Rank = ", np.linalg.matrix_rank(A))

Rank =  4


2.

In [6]:
A = np.array([[1,0,-1,2],
              [0,3,1,-1],
              [2,4,0,3],
              [-3,1,2,4]])
B = np.array([[1,2],
              [3,-1],
              [0,-1],
              [4,2]])
C = np.array([[3,8,0,5],
              [1,0,-4,8]])

D = C.dot(A).dot(B)
print(D)

[[147 -32]
 [ 33 -25]]


3.

In [3]:
Z = np.array([[-2,32,24],
              [92,66,25],
              [-80,40,20]])
print(round(np.linalg.det(Z)))

91520


4. 

In [7]:
P = np.array([[2,1,2],
              [1,0,1],
              [3,1,3]])
print(round(np.linalg.det(P)))
print(np.linalg.inv(P))

0
[[-6.0047995e+15 -6.0047995e+15  6.0047995e+15]
 [ 1.0000000e+00 -2.0000000e+00  0.0000000e+00]
 [ 6.0047995e+15  6.0047995e+15 -6.0047995e+15]]


8.

In [9]:
A = np.array([[2,0,0],
              [0,1,0],
              [0,0,5]])
print(sum(np.linalg.eigvals(A)))

8.0


9.

In [12]:
Z = np.array([[1,6,1],
              [1,2,3],
              [0,0,3]])
print(min(np.linalg.eigvals(Z)))

-1.0


16.

In [14]:
A = np.array([[6,-4,0],
             [3,8,3],
             [12,1,1]])
B = np.array([-14,25,-6])
print(np.linalg.solve(A,B))

[-1.  2.  4.]


AttributeError: 'numpy.ndarray' object has no attribute 'adjoint'